SET hive.mapred.supports.subdirectories=TRUE;
SET mapred.input.dir.recursive=TRUE;


drop table if exists temp.wms_product_label_merge_temp0 ;
create table if not exists temp.wms_product_label_merge_temp0 as select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,qc_computer_no ,qc_fail_reason ,packing_time ,shop_type ,1 as table_type from ods.wms_product_label_subject union all select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,null as qc_computer_no ,null as qc_fail_reason ,packing_time ,0 as shop_type ,2 as table_type from ods.wms__wms_product_label_201803 union all select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,null as qc_computer_no ,null as qc_fail_reason ,packing_time ,0 as shop_type ,3 as table_type from ods.wms__wms_product_label_old union all select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,null as qc_computer_no ,null as qc_fail_reason ,packing_time ,0 as shop_type ,4 as table_type from ods.wms_product_label_his union all select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,null as qc_computer_no ,null as qc_fail_reason ,packing_time ,0 as shop_type ,5 as table_type from ods.wms__wms_product_label_his ;

drop table if exists temp.wms_product_label_merge_temp1 ;
create table if not exists temp.wms_product_label_merge_temp1 as select * ,first_value(table_type) over (partition by product_label_id order by table_type) as first_table_type from temp.wms_product_label_merge_temp0 ;

drop table if exists temp.wms_product_label_merge_temp2 ;
create table if not exists temp.wms_product_label_merge_temp2 as select * ,date_add('${hivevar:day}',1) as update_date from temp.wms_product_label_merge_temp1 where table_type=first_table_type ;

insert overwrite table ods.wms_product_label_merge select product_label_id ,trade_id ,order_id ,ods_order_id ,product_label_no ,product_label_status ,receiving_scan_flag ,receiving_scan_time ,receiving_scan_operator ,qc_status ,qc_time ,print_task_id ,print_sequence ,label_print_flag ,label_print_time ,return_scan_flag ,return_scan_time ,return_scan_operator ,label_comment ,pms_receiving_scan_flag ,pms_receiving_scan_time ,remove_flag ,create_time ,creator ,update_time ,mender ,usable_flag ,qc_computer_no ,qc_fail_reason ,packing_time ,shop_type ,update_date from temp.wms_product_label_merge_temp2 ;
