create table if not exists `ods`.`t_shop` ( 
`id` int comment '',
`sid` bigint comment '淘宝店ID',
`ww_nickname` string comment '旺旺名称',
`tb_accountname` string comment '淘宝账号名称',
`cid` int comment '店铺所营类目',
`tag_category_id` int comment '店铺所营1级类目(已弃用)',
`province` string comment '省份',
`city` string comment '城市',
`logo` string comment 'logo',
`bid` int comment '商场(与 t_market 表subBid关联)',
`city_market_id` bigint comment '分站点ID',
`floor` int comment '楼层',
`type` int comment '类型 默认0 1整档 2分档',
`subarea` string comment '分区',
`position` string comment '档口位置',
`branch` string comment '分档档口号 大写字母A-H',
`address` string comment '详细地址',
`name` string comment '档口名称',
`discount_type` string comment '折扣运算符',
`discount_value` float comment '店铺折扣',
`telephone` string comment '电话',
`qq` string comment 'qq',
`wechat` string comment '微信号',
`update_time` string comment '更新时间',
`check_time` string comment '审核时间',
`expired_time` string comment '下架时间',
`item_up_time` string comment '商品最近上新时间',
`status` int comment '审核状态(0审核中 1正常 2已拒绝档口 3已下架档口 4档口变更旺旺)',
`ex_status` int comment '档口异常状态 0正常 11下午营业 12信息有误 13档口倒闭',
`user_id` int comment '用户id',
`is_tx` int comment '是否退现 0 否  1 是',
`is_sp` int comment '是否实拍 0 否  1 是',
`is_df` int comment '是否代发 0 否  1 是',
`category_html` string comment '分类的html',
`last_tid` bigint comment '最新的商品淘宝ID',
`total_items` int comment '店铺里面有效商品数',
`favorite_num` int comment '收藏次数',
`remark` string comment '备注',
`priority` float comment '权重，用于排序',
`contacts_name` string comment '店铺联系人名称,暂时没有使用',
`shop_auth_id` int comment '关联档口审核附件表',
`shop_auth_join_id` int comment '关联t_shop_auth_join表',
`shop_level` int comment '档口等级 1 顶级 2 优秀 3 中等 4 普通',
`cloud_update` int comment '是否秒更新 0否1是',
`cloud_update_expired_time` string comment '秒更新过期时间',
`start_business_date` string comment '开业日期',
`ranking_priority` double comment '档口排名权重',
`enter_time` string comment '档口入驻vvic平台时间',
`is_gold_shop` int comment '是否金牌档口  0 否 1是',
`first_ad_cate_id` int comment '主营1',
`second_ad_cate_id` int comment '主营2',
`refund_type` int comment '退款结算方式 1余额 2现金',
`label_one` int comment '标签外贸 1是0否',
`label_two` int comment '标签民族风 1是0否',
`label_three` int comment '情侣装标签',
`updown_reason` string comment '档口上下架原因 客服填写',
`ocs_mark` int comment '客服标注 0默认 1有备注 0没有备注 同ocs_remark关联',
`ocs_remark` string comment '客服标注备注',
`big_pic` string comment '大图',
`passwd` string comment '大图密码',
`showcase_update_time` string comment '橱窗推荐更新时间',
`has_recommended` int comment '橱窗推荐是否执行过',
`bp_status` int comment '大图审核状态',
`bp_check_user` string comment '大图审核人',
`bp_comment` string comment '大图审核备注',
`shop_type` int comment '档口类型 0：淘宝档口，1 vvic档口 ，默认为0',
`strength` int comment '是否实力质造 0：否 1：是',
`pangge_flag` int comment 'pangge业务开关，0关1开',
`lost_date` string comment '广告主流失日期',
`sp_flag` int comment '档口实拍黑白名单(0非名单 1正常 2白名单) 默认1',
`sp_flag_update_time` string comment '实拍更新时间',
`upload_weight` float comment '上传权重',
`be_vvicshop_time` string comment '首次成为vvic档口的时间',
`upload_weight_before` float comment '切换前上传权重',
`approve_status` int comment '审核状态（正常:0;先发后审:1）',
`approve_time` string comment '审核操作时间',
`approve_name` string comment '审核操作人',
`approve_remark` string comment '审核备注',
`pos_flag` int comment '打单状态 0：未开通 1：已开通 2：已停用',
`pos_time` string comment '首次开通打单时间',
`net_disk_id` string comment '网盘ID',
`tb_url` string comment '淘宝首页链接',
`vid` string comment '档口编码',
`supply_level` int comment '供货能力等级',
`merge_flag` int comment '拼团标记：0-关，1-开，2部分开放',
`refund_flag` int comment '档口退款权限开关：0：关闭，1：开启',
`is_delete` int comment '删除标识字段：0未删除，1已删除（店铺已删除，上下状态必然应该是下架）',
`is_df_declare` int comment '档口声明档口代发 -1 未配置 0 否 1 是',
`is_df_auth` int comment '搜款网审核档口代发 -1 未审核 0 否 1 是',
`is_df_auth_remark` string comment '搜款网审核档口代发备注',
`is_on_self_can_return` int comment '在架可退下架不退：1-支持 0-不支持(默认1)',
`is_special_goods_not_return` int comment '特价商品不退不换：1-支持 0-不支持(默认1)',
`is_member_shop` int comment '是否会员档口：1-是，0-否',
`member_expire_time` string comment '会员到期日期',
`quality_pass_rate` double comment '质检合格率' ) 
 stored as textfile 
 location 'hdfs://master:8020/user/hive/warehouse/ods.db/t_shop' ;